---
title: "Analysis"
author: "Elise Boos"
date: "2022-10-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages etc}
getwd()
#packages
require(tidyverse)
require(dplyr)
require(sf)
require(leaflet)
require(mapview)
require(readxl)
require(lubridate)
require(readxl)

library(unmarked)
library(AICcmodavg)
#make mapview work on a mac
mapviewOptions(fgb = FALSE)

#install flocker
#install.packages("remotes")
#remotes::install_github("jsocolar/flocker")

#remove.packages(c("StanHeaders", "rstan"))
#install.packages("StanHeaders", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
#install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))

#library(flocker)

#install.packages("camtrapR")
library(camtrapR)

#install.packages("ubms")
require(ubms)
```

```{r 2014 models }
camop2014 <- read.csv("camop_2014.csv", stringsAsFactors = TRUE)
data2014 <- read.csv("data2014_final.csv", stringsAsFactors =  TRUE)



camop2014 <- cameraOperation(camop2014, stationCol = "site", setupCol = "Date_Place", retrievalCol = "Last_Record_clean", occasionStartTime = 0 , dateFormat = "%Y-%m-%d", writecsv = FALSE)


detect_hist_2014_grayfox <- detectionHistory(recordTable = data2014, species = "Gray Fox", camOp= camop2014, output = "binary", stationCol = "site", speciesCol = "Species", day1 ="station", recordDateTimeCol = "date_time_obs", recordDateTimeFormat =  "%Y-%m-%d %H.%M", timeZone = "UTC", occasionLength = 1, includeEffort = TRUE, scaleEffort = FALSE, writecsv = FALSE)


```


```{r making occupancy dataframe 2015}

camop2015 <- read.csv("camop_2015.csv", stringsAsFactors = TRUE)
data2015 <- read.csv("data2015_final.csv", stringsAsFactors =  TRUE)


camop2015 <- cameraOperation(camop2015, stationCol = "site", setupCol = "Date_Place", retrievalCol = "Last.Record", occasionStartTime = 0 , dateFormat = "%Y-%m-%d", writecsv = FALSE)

detect_hist_2015_grayfox <- detectionHistory(recordTable = data2015, species = "Gray Fox", camOp= camop2015, output = "binary", stationCol = "site", speciesCol = "Species", day1 ="station", recordDateTimeCol = "date_time_obs", recordDateTimeFormat =  "%Y-%m-%d %H.%M", timeZone = "UTC", occasionLength = 1, includeEffort = TRUE, scaleEffort = FALSE, writecsv = FALSE)

detectionhist <- detect_hist_2015_grayfox$detection_history
```

```{r model 2015}
#sitecovs2017 <- data2015 %>%
 # select(site,Camera.Brand,Easting.1,Northing.1,Conservati,Active_Log,Hurricane,Fire_Damag,Landscape)

unmarkedFrame <- unmarkedFrameOccu(y = detectionhist, siteCovs = NULL, obsCovs = NULL)

summary(unmarkedFrame)

fm <- occu(formula = ~1
                     ~1,
           data = unmarkedFrame)
summary(fm)

backTransform(fm, type = "state")
backTransform(fm, type = "det")


##     (1 | site),)


#covariates <- read_xlsx("Covariates_cams.xlsx")

#cams700 <- covariates[188:263,]

#dataframe_det <- as.data.frame(detectionhist)
#dataframe_det$rn <- row.names(dataframe_det)


#join <- left_join(dataframe_det,cams700, by = c("rn" = "CameraID"))
#cams700_clean <- select(join, 116:215)
```

```{r 2017 analysis}
camop2017 <- read.csv("camop_2017.csv", stringsAsFactors = TRUE)
data2017 <- read.csv("data2017_final.csv", stringsAsFactors =  TRUE)

unique(camop2017$site)
unique(data2017$site)

camop2017 <- cameraOperation(camop2017, stationCol = "site", setupCol = "First_Obs", retrievalCol = "Last.Record_clean", occasionStartTime = 0 , dateFormat = "%Y-%m-%d", writecsv = FALSE)


detect_hist_2017_grayfox <- detectionHistory(recordTable = data2017, species = "Gray Fox", camOp= camop2017, output = "binary", stationCol = "site", speciesCol = "species.name", day1 ="station", recordDateTimeCol = "date_time_obs", recordDateTimeFormat =  "%Y-%m-%d %H.%M", timeZone = "UTC", occasionLength = 1, includeEffort = TRUE, scaleEffort = FALSE, writecsv = FALSE)

detectionhist <- detect_hist_2017_grayfox$detection_history

```

```{r model 2015}

sitecovs2017 <- data2017 %>%
  select(site,camera.brand,Logging, Easting,Northing,Conservati,Hurricane,Fire_Damag,Landscape)
sitecovs2017 <- sitecovs2017[!duplicated(sitecovs2017$site), ]

unmarkedFrame <- unmarkedFrameOccu(y = detectionhist, siteCovs = sitecovs2017, obsCovs = NULL)
summary(unmarkedFrame)

fm <- occu(formula = ~1
                     ~1,
           data = unmarkedFrame)
summary(fm)

backTransform(fm, type = "state")
backTransform(fm, type = "det")

###Random effect

model <- stan_occu(data = unmarkedFrame, formula = ~1 ~1)
model

output <- summary(model, "state")
logit<-output$mean[1]
  odds <- exp(logit)
  prob <- odds / (1 + odds)
prob

model_log <- stan_occu(data = unmarkedFrame, formula = ~1 ~Logging)
model_log
output <- summary(model_log, "state")
logit <- output$mean[2]
  odds <- exp(logit)
  prob2 <- odds / (1 + odds)
prob2

model_rand <- stan_occu(data = unmarkedFrame, formula = ~1 ~Logging + (1|site))
model_rand

output <- summary(model_rand, "state")
logit <- output$mean[2]
  odds <- exp(logit)
  prob <- odds / (1 + odds)
prob

prob;prob2
```


```{r 2018 analysis}
camop2018 <- read.csv("camop_2018.csv", stringsAsFactors = TRUE)
data2018 <- read.csv("data2018_final.csv", stringsAsFactors =  TRUE)

camop2018 <- cameraOperation(camop2018, stationCol = "site", setupCol = "First_Obs", retrievalCol = "Last.Record_clean", occasionStartTime = 0 , dateFormat = "%Y-%m-%d", writecsv = FALSE)


detect_hist_2018_grayfox <- detectionHistory(recordTable = data2018, species = "Gray Fox", camOp= camop2018, output = "binary", stationCol = "site", speciesCol = "species.name", day1 ="station", recordDateTimeCol = "date_time_obs", recordDateTimeFormat =  "%Y-%m-%d %H.%M", timeZone = "UTC", occasionLength = 1, includeEffort = TRUE, scaleEffort = FALSE, writecsv = FALSE)

detectionhist <- detect_hist_2018_grayfox$detection_history
```

```{r model 2018}
unmarkedFrame <- unmarkedFrameOccu(y = detectionhist, siteCovs = NULL, obsCovs = NULL)
summary(unmarkedFrame)

fm <- occu(formula = ~1
                     ~1,
           data = unmarkedFrame)
summary(fm)

backTransform(fm, type = "state")
backTransform(fm, type = "det")

```

