---
title: "Revisions"
author: "Elise Boos"
date: "2023-10-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
require(tidyverse)
require(mapview)
require(sf)
require(raster)

require(snowfall)

#install.packages("rjags")
require(rjags)
library(camtrapR)
```

## Post Rejection

```{r}
#Load and Clean Data 

##load dfs
load("dat.RData")
load("camop.RData")
covs_all <- read.csv("covs_fin.csv",stringsAsFactors = TRUE)

#fix logging column
covs_all$Logging <- ifelse(covs_all$Logging %in% c("No", "No Logging"), "No", "Yes")

#another option to rewrite factor
#library(forcats)
#covs_all2$Logging_fix <- fct_collapse(covs_all2$Logging, No = c("No","No Logging"), Yes = c("Yes","Logging"))

#missing lat and long 
covs_all[covs_all$site =="908F",]$Lat <- 17.66851300
covs_all[covs_all$site =="908F",]$Long <- -89.01283000



```

```{r}
# these sites missing easting northing 
# 508H <- 288991 , 1929840
# 502C <- 292758, 1955010
# 503C <- 291102, 1950731
# 506C <- 291308 , 1950725
# 511C <- 282077, 1935175
# 506F <- 283678, 1935452

camop[camop$site == "508H",]$Easting <- 288991
camop[camop$site == "508H",]$Northing <- 1929840

camop[camop$site == "502C",]$Easting <- 292758
camop[camop$site == "502C",]$Northing <- 1955010

camop[camop$site == "503C",]$Easting <- 291102
camop[camop$site == "503C",]$Northing <- 1950731

camop[camop$site == "506C",]$Easting <- 291308
camop[camop$site == "506C",]$Northing <- 1950725

camop[camop$site == "511C",]$Easting <- 282077
camop[camop$site == "511C",]$Northing <- 1935175

camop[camop$site == "506F",]$Easting <- 283678
camop[camop$site == "506F",]$Northing <- 1935452

#turn into spatial feautre
cams.sf <- camop %>%
 # drop_na(Easting, Northing) %>%
  st_as_sf(coords = c('Easting','Northing'),
           crs=26716)

#getting logging values attatched to cams 
join <- left_join(cams.sf, covs_all, by = "site")
```

```{r}
#visualize
mapview(join, zcol = "Logging")
mapview(filter(join, year(Date.Placement) == 2019), zcol = "Logging")
```

```{r}
### making grid
# Create an sf object for the grid
gridx <- seq(from = -89.1,to = -88.8, by = 0.01)
gridy <- seq(from = 17.4,to = 17.8, by = 0.01)


foo <- raster(xmn = -89.1, xmx = -88.8,
              ymn = 17.4, ymx =17.8,
              nrows = length(gridx),
              ncols = length(gridy)) %>% 
       rasterToPolygons() %>% 
       st_as_sf(
           crs=26716) %>% 
       mutate(group = 1:(length(gridx)*length(gridy))) %>% 
       st_cast("MULTIPOLYGON")

#transform to same crs
foo_trans <- st_transform(foo, crs(join))
#Now count how many data points exist in each grid
#mutate(foo,
 #      count = lengths(st_intersects(x = foo,  y = join))) -> foo
```

```{r}
# Draw a graphic

ggplot() +
  geom_sf(data = foo)+
  geom_sf(data = join)



mapview(foo_trans)+
  mapview(join, zcol = "Logging")

mapview(foo)+
mapview(filter(join, year(Date.Placement) == 2018), zcol = "Logging")
```

```{r}
grid <- st_join(join,
                foo_trans,
                left = F)

mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

```

# By Year 

```{r}
grid_2017 <-filter(grid, year(Date.Placement) == 2017)

Logging_Grid_2017 <- grid_2017 %>%
  group_by(group) %>%
  summarise(Logging_Grid = mode(Logging))

mapview(Logging_Grid_2017, zcol = "Logging_Grid")

Logging_Grid_2017.df <-dplyr::select(as.data.frame(Logging_Grid_2017), -geometry)

camgrid2017 <- left_join(grid_2017, Logging_Grid_2017.df, by = "group")

```

```{r 2018}
grid_2018 <-filter(grid, year(Date.Placement) == 2018)


Logging_Grid_2018 <- grid_2018 %>%
  group_by(group) %>%
  summarise(Logging_Grid = mode(Logging))

mapview(Logging_Grid_2018, zcol = "Logging_Grid")

Logging_Grid_2018.df <-dplyr::select(as.data.frame(Logging_Grid_2018), -geometry)

camgrid2018 <- left_join(grid_2018, Logging_Grid_2018.df, by = "group")

```

```{r 2019}
grid_2019  <-filter(grid, year(Date.Placement) == 2019)


Logging_Grid_2019 <- grid_2019 %>%
  group_by(group) %>%
  summarise(Logging_Grid = mode(Logging))

summary(Logging_Grid_2019$Logging_Grid)

mapview(Logging_Grid_2019, zcol = "Logging_Grid")

Logging_Grid_2019.df <-dplyr::select(as.data.frame(Logging_Grid_2019), -geometry)

camgrid2019 <- left_join(grid_2019, Logging_Grid_2019.df, by = "group")


```

```{r}
grid_2020 <-filter(grid, year(Date.Placement) == 2020)
# 2 2019 sites in here - move to 2019 or keep in 2020? Date placement was 2020

Logging_Grid_2020 <- grid_2020 %>%
  group_by(group) %>%
  summarise(Logging_Grid = mode(Logging))

mapview(Logging_Grid_2020, zcol = "Logging_Grid")

Logging_Grid_2020.df <-dplyr::select(as.data.frame(Logging_Grid_2020), -geometry)

camgrid2020 <- left_join(grid_2020, Logging_Grid_2020.df, by = "group")

```


```{r}

camgrid2017.df <- dplyr::select(as.data.frame(camgrid2017), -geometry)
cam_op <- cameraOperation(camgrid2017.df, stationCol = "group", cameraCol = "site", setupCol = "Date.Placement", byCamera = FALSE, allCamsOn = FALSE, camerasIndependent = FALSE,
                             retrievalCol = "Last.record", occasionStartTime = 0 , 
                             dateFormat = "%Y-%m-%d", writecsv = FALSE)


dat_2017 <-filter(dat, Year == 2017)
dat_2018 <-filter(dat, Year == 2018)
spillover_2017 <- dat_2018[1:17,]

dat_2017 <- rbind(dat_2017, spillover_2017)

datgrid2017 <- left_join(dat_2017, camgrid2017.df, by = "site")
```


## working out code 
```{r}
detect_hist_agouti <- detectionHistory(recordTable = datgrid2017, species = "Agouti",
                                       camOp = cam_op, output = "binary", stationCol = "group", 
                                       speciesCol = "Species", day1 ="station", 
                                       recordDateTimeCol = "date_time_obs", 
                                       recordDateTimeFormat =  "%Y-%m-%d %H.%M", 
                                       timeZone = "UTC", occasionLength = 1, 
                                       includeEffort = TRUE, scaleEffort = FALSE, 
                                       writecsv = FALSE)

detect_hist_puma <- detectionHistory(recordTable = datgrid2017, species = "Puma",
                                       camOp = cam_op, output = "binary", stationCol = "group", 
                                       speciesCol = "Species", day1 ="station", 
                                       recordDateTimeCol = "date_time_obs", 
                                       recordDateTimeFormat =  "%Y-%m-%d %H.%M", 
                                       timeZone = "UTC", occasionLength = 1, 
                                       includeEffort = TRUE, scaleEffort = FALSE, 
                                       writecsv = FALSE)
ylist <- list(Agouti=detect_hist_agouti$detection_history, Puma=detect_hist_puma$detection_history)

obs <- list(effort = detect_hist_agouti$effort)


Logging_Grid_2017.df$Logging_Grid <- as.factor(Logging_Grid_2017.df$Logging_Grid)
data_list <- list(ylist    = ylist,
                   siteCovs = Logging_Grid_2017.df,
                   obsCovs  = obs)  # is identical for all species

 modelfile1 <- tempfile(fileext = ".txt")
mod.jags <- communityModel(data_list,
                            occuCovs = list(fixed = "Logging_Grid"),
                            detCovsObservation = list(fixed = "effort"),
                            intercepts = list(det = "ranef", occu = "ranef"),
                            modelFile = modelfile1)

summary(mod.jags)


fit.jags <- fit(mod.jags,
                 n.iter = 1000,
                 n.burnin = 500,
                 chains = 3)

fit_summary <- summary(fit.jags)

DT::datatable(round(fit_summary$statistics, 3))

 plot_effects(mod.jags,
              fit.jags,
              submodel = "state")
 
  plot_effects(mod.jags,
              fit.jags,
              submodel = "det")
  

```

```{r}
Logging_Grid_2017.df$Logging_Grid <- as.factor(Logging_Grid_2017.df$Logging_Grid)
 # list of detection histories
datgrid2017$Species <- as.character(datgrid2017$Species)
#remove error rows if throws error 
datgrid20172 <- datgrid2017[-52,]
#check if runs all species

#get count of species
count <- table(datgrid20172$Species)
count
#count
list <- subset(count, count > 40)

species_list <- names(list)
species_list


 DetHist_list <- lapply(species_list, FUN = function(x) {
   detectionHistory(recordTable = datgrid20172, species = x,
                                       camOp = cam_op, output = "binary", stationCol = "group", 
                                       speciesCol = "Species", day1 ="station", 
                                       recordDateTimeCol = "date_time_obs", 
                                       recordDateTimeFormat =  "%Y-%m-%d %H.%M", 
                                       timeZone = "UTC", occasionLength = 1, 
                                       includeEffort = TRUE, scaleEffort = FALSE, 
                                       writecsv = FALSE)}
 )

 # assign species names to the list items
 names(DetHist_list) <- species_list
 #double check correct naming

 # note, DetHist_list is a list containing a list for each species
 ylist <- lapply(DetHist_list, FUN = function(x) x$detection_history)

data_list <- list(ylist    = ylist,
                   siteCovs = Logging_Grid_2017.df,
                   obsCovs  = list(effort = DetHist_list[[1]]$effort)) 

# text file to save the model
 modelfile1 <- tempfile(fileext = ".txt")

 mod.jags <- communityModel(data_list,
                            occuCovs = list(fixed = "Logging_Grid"),
                            detCovsObservation = list(fixed = "effort"),
                            intercepts = list(det = "ranef", occu = "ranef"),
                            modelFile = modelfile1)
summary(mod.jags)

 fit.jags <- fit(mod.jags,
                 n.iter = 1000,
                 n.burnin = 500,
                 chains = 3)
 
 fit_summary <- summary(fit.jags)
 
 DT::datatable(round(fit_summary$statistics, 3))
 
  plot_effects(mod.jags,
              fit.jags,
              submodel = "state")
  
   plot_effects(mod.jags,
              fit.jags,
              submodel = "det")
   
    plot_coef(mod.jags,
           fit.jags,
           submodel = "state")
   
```

```{r}
camgrid2018.df <- dplyr::select(as.data.frame(camgrid2018), -geometry)
cam_op <- cameraOperation(camgrid2018.df, stationCol = "group", cameraCol = "site", setupCol = "Date.Placement", byCamera = FALSE, allCamsOn = FALSE, camerasIndependent = FALSE,
                             retrievalCol = "Last.record", occasionStartTime = 0 , 
                             dateFormat = "%Y-%m-%d", writecsv = FALSE)

#some of the 2017 data goes through 2018 !!!
dat_2018  <-filter(dat, Year == 2018)
#removing 2017 data add back into 2017 or into this tbd 
dat_2018 <- dat_2018[-(1:17),]
datgrid2018 <- left_join(dat_2018, camgrid2018.df, by = "site")


 # list of detection histories
datgrid2018$Species <- as.character(datgrid2018$Species)
#remove error rows 
#datgrid20172 <- datgrid2017[-52,]

#get count of species
count <- table(datgrid2018$Species)
count
#count
list <- subset(count, count > 40)

species_list <- names(list)
species_list


 DetHist_list <- lapply(species_list, FUN = function(x) {
   detectionHistory(recordTable = datgrid2018, species = x,
                                       camOp = cam_op, output = "binary", stationCol = "group", 
                                       speciesCol = "Species", day1 ="station", 
                                       recordDateTimeCol = "date_time_obs", 
                                       recordDateTimeFormat =  "%Y-%m-%d %H.%M", 
                                       timeZone = "UTC", occasionLength = 1, 
                                       includeEffort = TRUE, scaleEffort = FALSE, 
                                       writecsv = FALSE)}
 )

 # assign species names to the list items
 names(DetHist_list) <- species_list

 # note, DetHist_list is a list containing a list for each species
 ylist <- lapply(DetHist_list, FUN = function(x) x$detection_history)

 Logging_Grid_2018.df$Logging_Grid <- as.factor(Logging_Grid_2018.df$Logging_Grid)
 
data_list <- list(ylist    = ylist,
                   siteCovs = Logging_Grid_2018.df,
                   obsCovs  = list(effort = DetHist_list[[1]]$effort)) 

# text file to save the model
 modelfile1 <- tempfile(fileext = ".txt")

 
 mod.jags <- communityModel(data_list,
                            occuCovs = list(fixed = "Logging_Grid"),
                            detCovsObservation = list(fixed = "effort"),
                            intercepts = list(det = "ranef", occu = "ranef"),
                            modelFile = modelfile1)
summary(mod.jags)

 fit.jags <- fit(mod.jags,
                 n.iter = 1000,
                 n.burnin = 500,
                 chains = 3)
 
 fit_summary <- summary(fit.jags)
 
 DT::datatable(round(fit_summary$statistics, 3))
 
  plot_effects(mod.jags,
              fit.jags,
              submodel = "state")
  
   plot_effects(mod.jags,
              fit.jags,
              submodel = "det")
   
    plot_coef(mod.jags,
           fit.jags,
           submodel = "state")

```


```{r}
camgrid2019.df <- dplyr::select(as.data.frame(camgrid2019), -geometry)
cam_op <- cameraOperation(camgrid2019.df, stationCol = "group", cameraCol = "site", setupCol = "Date.Placement", byCamera = FALSE, allCamsOn = FALSE, camerasIndependent = FALSE,
                             retrievalCol = "Last.record", occasionStartTime = 0 , 
                             dateFormat = "%Y-%m-%d", writecsv = FALSE)


dat_2019  <-filter(dat, Year == 2019)
# #removing 2017 data add back into 2017 or into this tbd 
# dat_2018 <- dat_2018[-(1:17),]
datgrid2019 <- left_join(dat_2019, camgrid2019.df, by = "site")


 # list of detection histories
datgrid2019$Species <- as.character(datgrid2019$Species)
#remove error rows 
datgrid20192 <- datgrid2019[-2227,]

#get count of species
count <- table(datgrid20192$Species)
count
#count
list <- subset(count, count > 40)

species_list <- names(list)
species_list


 DetHist_list <- lapply(species_list, FUN = function(x) {
   detectionHistory(recordTable = datgrid20192, species = x,
                                       camOp = cam_op, output = "binary", stationCol = "group", 
                                       speciesCol = "Species", day1 ="station", 
                                       recordDateTimeCol = "date_time_obs", 
                                       recordDateTimeFormat =  "%Y-%m-%d %H.%M", 
                                       timeZone = "UTC", occasionLength = 1, 
                                       includeEffort = TRUE, scaleEffort = FALSE, 
                                       writecsv = FALSE)}
 )

 # assign species names to the list items
 names(DetHist_list) <- species_list

 # note, DetHist_list is a list containing a list for each species
 ylist <- lapply(DetHist_list, FUN = function(x) x$detection_history)

 Logging_Grid_2019.df$Logging_Grid <- as.factor(Logging_Grid_2019.df$Logging_Grid)
 
data_list <- list(ylist    = ylist,
                   siteCovs = Logging_Grid_2019.df,
                   obsCovs  = list(effort = DetHist_list[[1]]$effort)) 

# text file to save the model
 modelfile1 <- tempfile(fileext = ".txt")

 
 mod.jags <- communityModel(data_list,
                            occuCovs = list(fixed = "Logging_Grid"),
                            detCovsObservation = list(fixed = "effort"),
                            intercepts = list(det = "ranef", occu = "ranef"),
                            modelFile = modelfile1)
summary(mod.jags)

 fit.jags <- fit(mod.jags,
                 n.iter = 1000,
                 n.burnin = 500,
                 chains = 3)
 
 fit_summary <- summary(fit.jags)
 
 DT::datatable(round(fit_summary$statistics, 3))
 
  plot_effects(mod.jags,
              fit.jags,
              submodel = "state")
  
   plot_effects(mod.jags,
              fit.jags,
              submodel = "det")
   
    plot_coef(mod.jags,
           fit.jags,
           submodel = "state")

```


```{r}
camgrid2020.df <- dplyr::select(as.data.frame(camgrid2020), -geometry)
cam_op <- cameraOperation(camgrid2020.df, stationCol = "group", cameraCol = "site", setupCol = "Date.Placement", byCamera = FALSE, allCamsOn = FALSE, camerasIndependent = FALSE,
                             retrievalCol = "Last.record", occasionStartTime = 0 , 
                             dateFormat = "%Y-%m-%d", writecsv = FALSE)


dat_2020  <-filter(dat, Year == 2020)
# #removing 2017 data add back into 2017 or into this tbd 
 dat_2020 <- dat_2020[-(1:50),]
datgrid2020 <- left_join(dat_2020, camgrid2020.df, by = "site")


 # list of detection histories
datgrid2020$Species <- as.character(datgrid2020$Species)
#remove error rows 
datgrid20202 <- datgrid2020[-1019,]

#get count of species
count <- table(datgrid20202$Species)
count
#count
list <- subset(count, count > 40)

species_list <- names(list)
species_list


 DetHist_list <- lapply(species_list, FUN = function(x) {
   detectionHistory(recordTable = datgrid20202, species = x,
                                       camOp = cam_op, output = "binary", stationCol = "group", 
                                       speciesCol = "Species", day1 ="station", 
                                       recordDateTimeCol = "date_time_obs", 
                                       recordDateTimeFormat =  "%Y-%m-%d %H.%M", 
                                       timeZone = "UTC", occasionLength = 1, 
                                       includeEffort = TRUE, scaleEffort = FALSE, 
                                       writecsv = FALSE)}
 )

 # assign species names to the list items
 names(DetHist_list) <- species_list

 # note, DetHist_list is a list containing a list for each species
 ylist <- lapply(DetHist_list, FUN = function(x) x$detection_history)

 Logging_Grid_2020.df$Logging_Grid <- as.factor(Logging_Grid_2020.df$Logging_Grid)
 
data_list <- list(ylist    = ylist,
                   siteCovs = Logging_Grid_2020.df,
                   obsCovs  = list(effort = DetHist_list[[1]]$effort)) 

# text file to save the model
 modelfile1 <- tempfile(fileext = ".txt")

 
 mod.jags <- communityModel(data_list,
                            occuCovs = list(fixed = "Logging_Grid"),
                            detCovsObservation = list(fixed = "effort"),
                            intercepts = list(det = "ranef", occu = "ranef"),
                            modelFile = modelfile1)
summary(mod.jags)

 fit.jags <- fit(mod.jags,
                 n.iter = 1000,
                 n.burnin = 500,
                 chains = 3)
 
 fit_summary <- summary(fit.jags)
 
 DT::datatable(round(fit_summary$statistics, 3))
 
  plot_effects(mod.jags,
              fit.jags,
              submodel = "state")
  
   plot_effects(mod.jags,
              fit.jags,
              submodel = "det")
   
    plot_coef(mod.jags,
           fit.jags,
           submodel = "state")

```

